### PR TITLE
Fix message as to when tool will expire

### PR DESCRIPTION
**Pull request by robertberry-zz**

### CODE REVIEW

**Comment by JustinPinner** [comment]
Does that mean it effectively always says it'll be switched off at the end of next month? Ha :+1:

**Comment by gklopper** [comment]
actually I agreed with David B that it could stay one more quarter as they have promised to take over ownership, otherwise it would already be dead...

**Comment by stephanfowler** [comment]
:+1: please refactor as a generic "Klopper Banner"

**Comment by robertberry-zz** [comment]
klopper.js

**Comment by johnduffell** [comment]
haha

**Pull request merged**
